update google-cloud-run.yml

diff --git a/.github/workflows/google-cloudrun.yml b/.github/workflows/google-cloudrun.yml
--- a/.github/workflows/google-cloudrun.yml
+++ b/.github/workflows/google-cloudrun.yml
@@ -1,61 +1,14 @@
-# This workflow build and push a Docker container to Google Artifact Registry and deploy it on Cloud Run when a commit is pushed to the "main" branch
-#
-# Overview:
-#
-# 1. Authenticate to Google Cloud
-# 2. Authenticate Docker to Artifact Registry
-# 3. Build a docker container
-# 4. Publish it to Google Artifact Registry
-# 5. Deploy it to Cloud Run
-#
-# To configure this workflow:
-#
-# 1. Ensure the required Google Cloud APIs are enabled:
-#
-#    Cloud Run            run.googleapis.com
-#    Artifact Registry    artifactregistry.googleapis.com
-#
-# 2. Create and configure Workload Identity Federation for GitHub (https://github.com/google-github-actions/auth#setting-up-workload-identity-federation)
-#
-# 3. Ensure the required IAM permissions are granted
-#
-#    Cloud Run
-#      roles/run.admin
-#      roles/iam.serviceAccountUser     (to act as the Cloud Run runtime service account)
-#
-#    Artifact Registry
-#      roles/artifactregistry.admin     (project or repository level)
-#
-#    NOTE: You should always follow the principle of least privilege when assigning IAM roles
-#
-# 4. Create GitHub secrets for WIF_PROVIDER and WIF_SERVICE_ACCOUNT
-#
-# 5. Change the values for the GAR_LOCATION, SERVICE and REGION environment variables (below).
-#
-# NOTE: To use Google Container Registry instead, replace ${{ env.GAR_LOCATION }}-docker.pkg.dev with gcr.io
-#
-# For more support on how to run this workflow, please visit https://github.com/marketplace/actions/deploy-to-cloud-run
-#
-# Further reading:
-#   Cloud Run IAM permissions                 - https://cloud.google.com/run/docs/deploying
-#   Artifact Registry IAM permissions         - https://cloud.google.com/artifact-registry/docs/access-control#roles
-#   Container Registry vs Artifact Registry   - https://cloud.google.com/blog/products/application-development/understanding-artifact-registry-vs-container-registry
-#   Principle of least privilege              - https://cloud.google.com/blog/products/identity-security/dont-get-pwned-practicing-the-principle-of-least-privilege
-
-name: Build and Deploy to Cloud Run
+name: Build, Test, and Deploy to GCP Kubernetes
 
 on:
-  #  push:
-  #    branches:
-  #      - "main"
   workflow_dispatch:
 
 env:
-  PROJECT_ID: srilanka-zss-poc-d # TODO: update Google Cloud project id
-  GAR_LOCATION: us-central1 # TODO: update Artifact Registry location
-  REPOSITORY: demo-gradle
-  SERVICE: github-build-deploy-cloudrun # TODO: update Cloud Run service name
-  REGION: us-central1 # TODO: update Cloud Run service region
+  DOCKER_REPO: dg4285/harmonix-dev # TODO: Update your Docker Hub repository
+  IMAGE_NAME: test-image-name              # TODO: Update your service name
+  PROJECT_ID: srilanka-zss-poc-d            # TODO: Update your GCP project id
+  K8S_CLUSTER: harmonix-dev-cluster             # TODO: Update your Kubernetes cluster name
+  K8S_REGION: us-central1            # TODO: Update your Kubernetes cluster region
 
 jobs:
   build:
@@ -76,42 +29,48 @@ jobs:
       - name: Grant execute permission for gradlew
         run: chmod +x ./gradlew
 
-      - name: Google Auth
-        id: auth
-        uses: 'google-github-actions/auth@v1'
+      - name: Run Unit Tests with Coverage
+        run: |-
+          ./gradlew test jacocoTestReport
+          COVERAGE=$(./gradlew jacocoTestReport | grep 'Total Coverage' | awk '{print $NF}' | sed 's/%//')
+          echo "Coverage: $COVERAGE%"
+          if [ "$COVERAGE" -lt 80 ]; then
+            echo "Unit test coverage is below 80%. Failing build."
+            exit 1
+          fi
+
+      - name: Save Coverage Report
+        run: |-
+          tar -czf coverage-report.tar.gz build/reports/jacoco
+          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+          docker create -v /coverage --name coverage-container busybox
+          docker cp coverage-report.tar.gz coverage-container:/coverage/
+          docker commit coverage-container ${{ env.DOCKER_REPO }}/coverage-report:${{ github.sha }}
+          docker push ${{ env.DOCKER_REPO }}/coverage-report:${{ github.sha }}
+
+      - name: Build and Push Docker Image
+        run: |-
+          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+          docker build -t ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
+          docker push ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
+
+      - name: Authenticate to GCP
+        uses: google-github-actions/auth@v1
         with:
           token_format: 'access_token'
           workload_identity_provider: projects/73029603858/locations/global/workloadIdentityPools/my-pool/providers/github-provider
-          service_account: github-build-deploy-cloudrun@srilanka-zss-poc-d.iam.gserviceaccount.com
+          service_account: github-build-deploy-cloudrun@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
 
-      # NOTE: Alternative option - authentication via credentials json
-      # - name: Google Auth
-      #   id: auth
-      #   uses: 'google-github-actions/auth@v0'
-      #   with:
-      #     credentials_json: '${{ secrets.GCP_CREDENTIALS }}''
+      - name: Set up gcloud CLI
+        uses: google-github-actions/setup-gcloud@v1
+        with:
+          project_id: ${{ env.PROJECT_ID }}
 
-      # BEGIN - Docker auth and build (NOTE: If you already have a container image, these Docker steps can be omitted)
-
-      # Authenticate Docker to Google Cloud Artifact Registry
-      - name: Build and Push Container
+      - name: Connect to GCP Kubernetes Cluster
         run: |-
-          ./gradlew jib --image="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
+          gcloud container clusters get-credentials ${{ env.K8S_CLUSTER }} --region ${{ env.K8S_REGION }} --project ${{ env.PROJECT_ID }}
 
-      # END - Docker auth and build
-
-      - name: Deploy to Cloud Run
-        id: deploy
+      - name: Deploy to GCP Kubernetes
         run: |-
-            gcloud run deploy ${{ env.SERVICE }} \
-              --image ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }} \
-              --quiet \
-              --platform managed \
-              --region ${{ env.REGION }} \
-              --project ${{ env.PROJECT_ID }} \
-              --format json \
-              --allow-unauthenticated
-
-      # If required, use the Cloud Run url output in later steps
-      - name: Show Output
-        run: echo ${{ steps.deploy.outputs.url }}
+          kubectl set image deployment/${{ env.IMAGE_NAME }} ${env.IMAGE_NAME}=${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
+          kubectl rollout status deployment/${{ env.IMAGE_NAME }}
